language: vim

before_script: |
  git clone https://github.com/junegunn/vader.vim.git
  git clone https://github.com/KimNorgaard/kronos.vim.git
  git branch add-undo-task

script: |
  TZ=UTC vim -Nu <(cat << VIMRC
  filetype off
  set rtp+=vader.vim
  set rtp+=kronos.vim
  set rtp+=.
  set rtp+=after
  filetype plugin indent on
  syntax enable
  VIMRC) -c 'Vader! autoload/kronos/**/*.vader' > /dev/null

